=== fredboudon/lpy/src/openalea/lpy/lsysparameters/schema/lpy.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "L-Py",
    "type": "object",
    "required": [
        "schema",
        "version"
    ],
    "properties": {
        "schema": {
            "enum": ["lpy"]
        },
        "version": {
            "type": "string"
        },
        "options": {
            "$ref": "options.json"
        },
        "parameters": {
            "type": "array",
            "items": {
                "$ref": "category.json"
            }
        },
        "materials": {
            "type": "array",
            "items": {
                "$ref": "appearance.json"
            }
        },
        "credits" : {
            "$ref": "credits.json"            
        }
    }
}

=== fredboudon/lpy/share/tutorial/01 - turtle/08 - texturedpatch.json
{
    "schema": "lpy",
    "version": "1.1",
    "options": {
        "compilation": {},
        "matching": {},
        "processing": {},
        "interaction": {}
    },
    "parameters": [
        {
            "name": "Panel 1",
            "enabled": true,
            "scalars": [],
            "curves": []
        }
    ],
    "materials": []
}

=== fredboudon/lpy/share/tutorial/01 - turtle/10 - rotations.json
{
    "schema": "lpy",
    "version": "1.1",
    "options": {
        "compilation": {},
        "matching": {},
        "processing": {},
        "interaction": {}
    },
    "parameters": [
        {
            "name": "Panel 1",
            "enabled": true,
            "scalars": [],
            "curves": []
        }
    ],
    "materials": [
        {
            "index": 7,
            "name": "Color_7",
            "ambient": [
                15,
                15,
                15
            ],
            "specular": [
                0,
                0,
                0
            ],
            "emission": [
                0,
                0,
                0
            ],
            "diffuse": 7.0,
            "transparency": 0.0,
            "shininess": 0.2
        }
    ]
}

=== fredboudon/lpy/share/tutorial/02 - fractals/peanocurve.json
{
    "schema": "lpy",
    "version": "1.1",
    "options": {
        "compilation": {},
        "matching": {},
        "processing": {},
        "interaction": {}
    },
    "parameters": [],
    "materials": [
        {
            "index": 1,
            "name": "Color_1",
            "ambient": [
                0,
                0,
                0
            ],
            "specular": [
                0,
                0,
                0
            ],
            "emission": [
                0,
                0,
                0
            ],
            "diffuse": 3.0,
            "transparency": 0.0,
            "shininess": 0.2
        },
        {
            "index": 3,
            "name": "Color_3",
            "ambient": [
                175,
                0,
                0
            ],
            "specular": [
                0,
                0,
                0
            ],
            "emission": [
                0,
                0,
                0
            ],
            "diffuse": 1.02857,
            "transparency": 0.0,
            "shininess": 0.2
        }
    ]
}
